### PR TITLE
Create st7789_240x135_simpletest_Pimoroni_Pico_Display_Pack.py

### PR DESCRIPTION
**Pull request by wildestpixel**
Adding functionality simply for Pimoroni Pico Display Pack

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Thank you! Please include a license header similar to this one: https://github.com/adafruit/Adafruit_CircuitPython_ST7789/blob/master/examples/st7789_simpletest.py#L1-L2

**Review by wildestpixel — COMMENTED** [review]
Added license

**Review by ladyada — APPROVED** [review]
lgtm!

**Review by tannewt — APPROVED** [review]
Thank you! (Feel free to add yourself to the license in a follow up PR if you like.)

**Pull request merged**
