### PR TITLE
Create st7789_240x240_simpletest_Pimoroni_Pico_Explorer.py

### PR DESCRIPTION
**Pull request by wildestpixel**
Example for Pimoroni Pico Explorer Display, correctly rotated

### CODE REVIEW

**Comment by ladyada** [comment]
thanks please check the CI error to get CI passing then let us know its ready for review

**Comment by wildestpixel** [comment]
Sorry @ladyada - this is defeating me as a complete novice on CI check's to know how to get past the failing on black. The code is the same as the simpletest with the change of the pi assignments and inclusion of import busio as pico has no assignment for SPI pins in board.

**Comment by tannewt** [comment]
Are you editing the repo locally? Installing pre-commit can simplify this: https://pre-commit.com/#installation It'll auto-fix the files for you.

**Comment by dherrada** [comment]
@wildestpixel Hey. Thanks for adding that example. What @tannewt said is definitely correct, but since you're new to CIs, and the only check that is failing is the Black check, you _should_ be able to get by just installing and running Black. There's a guide page on doing that here (https://learn.adafruit.com/improve-your-code-with-pylint/black) but the gist of it is that you install it with:
```
pip install black
```
or
```
pip3 install black
```
and then run it with:
```
black --target-version=py35 .
```
in the repository folder.

**Comment by wildestpixel** [comment]
Will get on this shortly, had hectic few work days and new Mac to migrate to, thanks for the guidance :)

**Review by tannewt — APPROVED** [review]
Thank you @wildestpixel! Hope you are liking your new Mac!

**Pull request merged**
